version: '3'

services:
  db:
    image: 'postgres:10-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    env_file:
      - .env.prod
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=98ac23fbac05280c5c20337b6a91c829be9ad17db631bd188ae46b86cf95a745d91c4d03038f0ffce9a6b932875cc7b4604b76ef34adfdf82bfef522a35692b9

volumes:
  redis:
  postgres:
